### ISSUE TITLE
PyPi pip install fails

### ISSUE THREAD

**Issue by autumnjolitz** [mjpieters/rtfunicode#1]
```
(cpython27) benjolitz-laptop:~/software $ pip install rtfunicode
Collecting rtfunicode
  Using cached rtfunicode-1.3.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/y3/ddl3hd9j6d54fv2kd5x804lc0000gp/T/pip-build-pWQk9Q/rtfunicode/setup.py", line 11, in <module>
        open('CHANGES.rst').read(),
    IOError: [Errno 2] No such file or directory: 'CHANGES.rst'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/y3/ddl3hd9j6d54fv2kd5x804lc0000gp/T/pip-build-pWQk9Q/rtfunicode/
```

**Comment by gnulnx** [comment]
Also having the same problem.  It's strange because you can see the file in the repo.  In any event you can work around this by hand by opening the rtfunicode/setup.py file and commenting out the line with open('CHANGES.rst').read().

my suspicion is the file was not included when the PyPi stuff was created.

**Comment by mjpieters** [comment]
I need to add a MANIFEST.in, because CHANGES.rst is not included by default. Fix coming up!

**Comment by mjpieters** [comment]
New release 1.4 on PyPI installs cleanly for me, sorry for not having properly tested that last step.

**Comment by gnulnx** [comment]
@mjpieters  Thank for resolving this so quickly!
